### ISSUE TITLE
Python not installed

### ISSUE THREAD

**Issue by UncommonGarb** [rocky4546/tvheadend-locast#10]
It continues to say I do not have python installed when I have it installed in 2 ways. 1, from the windows store and 2, from the installer. I have attempted to install it with the installer with just my user as well as all users. It does not see python and cancels the install of the software.

**Comment by rocky4546** [comment]
Sorry about that.  That part of the installer just got a face lift, so not sure why you are having issues.

First let me thank you for trying the product.  I am actively working this and adding tons of new features as I can.  In the meantime, I would be interested in a short test that does what the installer is trying.

From a CMD window run the command
<pre>
    where python
</pre>
The installer runs a batch file that basically runs that script and if it gets an answer, says everything is ok.  The installer needs the path in order to setup the service to run the app. You can also find the script the installer runs at
https://github.com/rocky4546/tvheadend-locast/tree/main/build/WINDOWS
called findpython.bat
Downloading the script and running that from the CMD window will let you know if there is an issue running bat files.  Let me know what you find, since I am trying to have this to be easy to use.

**Comment by rocky4546** [comment]
I did a little checking and here is what I found so far.  I uninstalled python from my system and went to MS Store and installed from there.  I have a feeling that the issue is with the MS Windows install of python. I am a little aware of what MS is doing on this install.  I then tried the "where python" command and it said it did not exist.  Found out that MS does not link the python.exe to your apps area.  Only python3.9.exe, pythonw.exe, pythonw3.9.exe and pythonw3.exe.  Also, MS installs python so only a single user can use it.  The service user (SYSTEM) would not be able to access the python install.  This is why python needed to be installed in the program files area.

I then went through the tvheadend-locast installer.  It could not find "where python" as you indicated and as indicated above, this is expected.  It did have the "Install for all users" checked, so that should install it in the program files area and indeed it was set to install at C:\Program Files\Python39.  After installing python, it still could not find the python.exe so it recommended restarting the installer which is probably normal.  My old CMD window still could not find python, but when I brought up a new cmd window, the where python worked.

The next time I ran the installer as recommended, it did find the python installed at C:\Program Files\Python39\python.exe. No need to reinstall python again so, this time the "Install Python3" is unchecked.  The installer ran through to completion. The installer does not automatically start the service (on purpose), so I brought up Services and started TVHeadend-Locast.  No issue reported.  In my browser I typed 
http://localhost:6077/
and it brought up the app.  So, far everything is as expected.

**Comment by UncommonGarb** [comment]
Do you have a discord or telegram or something? Maybe can chat back and
forth.

**Comment by rocky4546** [comment]
I have created a discord account for rocky4546.

**Comment by rocky4546** [comment]
rocky4546#8998

**Comment by rocky4546** [comment]
Issue was associated with using GIT executables in stall the user did not have.
User was able to install with 0.8.3a
