### ISSUE TITLE
[BUG] plex_accessible_ip is not configable in the config.ini file

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [rocky4546/tvheadend-locast#14]
I have 

```
[web]
plex_accessible_ip = xxx.xxx.xxx.xxx
```
in my config.ini file but when I restart tvheadend-locast the ip does not update. And the web UI has it grayed out so I can't change it manually there.

**Comment by rocky4546** [comment]
Yea, I tried to get away from any plex naming in the config file from the locast2plex (but still has a few of them).  If you go to the web portal at http://ipaddress:6077/ and look at Settings>Client
You will see the parameter local_ip.  Use this instead of plex_accessible_ip.  plex_accessible_ip is automatically set, which is why it is read-only.

If you still have an issue, let us know.

**Comment by cookie-monster-bit** [comment]
The plex_accessible_ip is used for the channels.m3u. And since tvheadend-locast automatically sets it to my docker container I need to be able to override this.

**Comment by rocky4546** [comment]
The need to override the 0.0.0.0 binding is primarily for Docker containers, which is your case, so I completely agree.  By setting the local ip value to your ip address, the binding will change from 0.0.0.0 to the ip address you set.  To see this, change the local_ip value and save it, then restart the app docker service and it should now be on that IP address and not on 0.0.0.0.  You should be able to go to the web portal on that ip address and see that the plex value is now set to whatever the local ip value you set.

**Comment by cookie-monster-bit** [comment]
So, I'm probably a special use case, as I need the plex_accessible_ip and bind_ip to be separate ip's. I'm trying to bind the ip on the local docker container but have plex_accessible_ip my host ip, as I'm on a hosted server, so I can pass that ip to another container.

**Comment by rocky4546** [comment]
Are you using the -p 6077:6077 to push the port to the host ip?

**Comment by cookie-monster-bit** [comment]
Yes, I do.

**Comment by rocky4546** [comment]
I understand. You need the plex ip value to be set so that the channels.m3u has a different ip address than the one bound to port 6077, which it does not do right now (it somehow got changed, sorry about that).  Give me some time and I will have an update out today.  The repo moved and I am now working out of
https://github.com/cabernetwork/cabernet/
I will push the change there.

**Comment by rocky4546** [comment]
Question...
I am currently using the plex_accessible_ip value to callback to the web portal from the app.  From within the docker can the app see the external ip or does the app need to use the internal ip addess to call http://ipaddress:6077/
thanks

**Comment by rocky4546** [comment]
I decided to use localhost for the ipaddress.  It should work with Docker, linux and windows.  Pushed a release to test at
https://github.com/cabernetwork/cabernet/releases/tag/0.9.0.5
The 0.9.* versions now come with auto-upgrade capabilities, so upgrading will be less of an issue.  Not sure what version you are currently running, but if it is 0.8.8*, then you should be fine with a source overlay.

**Comment by cookie-monster-bit** [comment]
Thank you! It works perfect now!
